Fixes broken link
kubernetes-sigs/slack-infra pull request #61
Opened 2022-09-17 06:45 UTC by amolmote

Signed-off-by: amolmote <amolmote201@gmail.com>
Fixes #60

2022-09-19 08:18 UTC, cpanato reviewed
/ok-to-test

2022-09-19 08:21 UTC, cpanato requested changes
thanks

a small request

2022-09-19 08:21 UTC, cpanato commented on CONTRIBUTING.md
> +- [Contributor Cheat Sheet](https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README.md) - Common resources for existing developers
```suggestion
- [Contributor Cheat Sheet](https://www.kubernetes.dev/docs/contributor-cheatsheet/) - Common resources for existing developers
```

2022-09-19 08:28 UTC, amolmote commented on CONTRIBUTING.md
> +- [Contributor Cheat Sheet](https://github.com/kubernetes/community/blob/master/contributors/guide/contributor-cheatsheet/README.md) - Common resources for existing developers
ok I commit your suggestion and squash it. thank you @cpanato

2022-09-19 08:30 UTC, cpanato approved these changes
/lgtm
/approve

2022-09-19 08:31 UTC, cpanato commented
/assign @nikhita

for approval :)

2022-09-19 08:33 UTC, cpanato reviewed
/lgtm

2022-10-03 02:53 UTC, amolmote commented
@cpanato can we use this https://k8s.dev/cheatsheet shorter version of link here. Bobby suggested me this link.
what do you think?

2022-10-03 10:48 UTC, cpanato commented
Sound great

2022-10-07 04:01 UTC, amolmote commented
> Sound great
done @cpanato, I have updated the link with shorter format. it looks good

2022-10-07 04:08 UTC, cpanato approved these changes
/lgtm

2022-12-31 19:22 UTC, BenTheElder commented
/assign @jeefy

2023-04-01 09:40 UTC, cpanato commented
lets get this merged 
/assign @nikhita

2023-04-03 02:17 UTC, nikhita approved these changes
/lgtm
/approve

/woof

2023-04-03 02:21 UTC, merged